### ISSUE TITLE
Match the interface with the one of the page on the website.

### ISSUE THREAD

**Issue by DeeRaudh** [rkajau/cipta#2]
I need the user-interface to look similar to the page below:
http://www.utb.edu.bn/cipta/cipta/about/
<img width="1360" alt="Screenshot 2020-06-17 21 15 44" src="https://user-images.githubusercontent.com/47495255/84902804-de2e6700-b0df-11ea-9463-a0768c16fa25.png">

The application should be in the location as shown in the picture.
Login Page is not affected by this issue.

**Comment by rkajau** [comment]
Fixed issue #2
